version: "3"
   
services:
  postgis:
    image: postgis/postgis
    deploy:
      resources:
        limits:
          memory: 300M
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - "5432:5432"
    restart: always
    container_name: postgis

  geo-gaman:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "8001:8001"
    depends_on:
      - postgis
    command: /code/compose/django/start.sh
    restart: always
    container_name: geo-gaman