# Generated by Django 4.0.2 on 2022-04-26 16:16

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codename', models.SlugField(unique=True)),
                ('order', models.IntegerField(choices=[(1, 'Country'), (2, 'State'), (3, 'City'), (4, 'Place')])),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('events_ids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveBigIntegerField(), blank=True, null=True, size=None)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='zones.zone')),
                ('zones', models.ManyToManyField(blank=True, to='zones.Zone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
