# Generated by Django 4.0.2 on 2022-04-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date time on which the was updated.', verbose_name='updated at')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('start', models.DateField(help_text='sport event start date')),
                ('finish', models.DateField(help_text='sport event finish date')),
                ('geolocation', models.CharField(max_length=33)),
                ('country', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=90)),
                ('place', models.CharField(max_length=180)),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
